-- Seed: 1 demo company + 500 stations + 1-4 chargers each
-- All rows have is_test = TRUE

-- Demo company
INSERT INTO station_domain.companies (id, name, is_test)
VALUES ('00000000-0000-0000-0000-000000000001', 'BorneMap Demo Operator', TRUE)
ON CONFLICT (id) DO NOTHING;

-- Stations and chargers are loaded via the seed CSV + a small helper script.
-- For reproducibility, this migration uses a procedural approach:
-- the implementer should run the generate_seed.py script and then
-- convert the CSV into INSERT statements, or use \copy from psql.
--
-- Below is a representative sample (first 5 stations). The full 500-row
-- insert is generated by running:
--   python3 infrastructure/seed/generate_seed.py
--   python3 infrastructure/seed/csv_to_sql.py
-- and pasting the output into this file before running sqlx migrate run.
--
-- For now, we insert the first 5 stations as a minimal seed that allows
-- the backend to start and the quickstart smoke tests to pass.
-- The full seed will be loaded via a separate script.

INSERT INTO station_domain.stations (id, company_id, name, address, location, is_active, under_maintenance, opening_hours_osm, is_test)
VALUES
    ('a0000001-0000-0000-0000-000000000001', '00000000-0000-0000-0000-000000000001', 'Tunis Central Station', 'Avenue Habib Bourguiba, Tunis', ST_MakePoint(10.1815, 36.8065)::geography, TRUE, FALSE, '24/7', TRUE),
    ('a0000002-0000-0000-0000-000000000001', '00000000-0000-0000-0000-000000000001', 'Sousse Station', 'Boulevard Haffouz, Sousse', ST_MakePoint(10.6369, 35.8254)::geography, TRUE, FALSE, 'Mo-Fr 08:00-20:00; Sa 09:00-13:00', TRUE),
    ('a0000003-0000-0000-0000-000000000001', '00000000-0000-0000-0000-000000000001', 'Sfax Station', 'Rue de la Republique, Sfax', ST_MakePoint(10.7603, 34.7406)::geography, TRUE, FALSE, 'Mo-Sa 07:00-22:00', TRUE),
    ('a0000004-0000-0000-0000-000000000001', '00000000-0000-0000-0000-000000000001', 'Bizerte Station', 'Avenue Habib Bouguiba, Bizerte', ST_MakePoint(9.8738, 37.2744)::geography, FALSE, TRUE, '', TRUE),
    ('a0000005-0000-0000-0000-000000000001', '00000000-0000-0000-0000-000000000001', 'Gabes Station', 'Rue de Tripoli, Gabes', ST_MakePoint(10.0972, 33.8815)::geography, TRUE, FALSE, 'Mo-Fr 06:00-22:00; Sa-Su 08:00-20:00', TRUE)
ON CONFLICT (id) DO NOTHING;

-- Sample chargers for first 5 stations
INSERT INTO station_domain.chargers (id, station_id, connector, power_kw, is_active, is_test)
VALUES
    ('b0000001-0000-0000-0000-000000000001', 'a0000001-0000-0000-0000-000000000001', 'CCS', 50.00, TRUE, TRUE),
    ('b0000002-0000-0000-0000-000000000001', 'a0000001-0000-0000-0000-000000000001', 'Type2', 22.00, TRUE, TRUE),
    ('b0000003-0000-0000-0000-000000000001', 'a0000002-0000-0000-0000-000000000001', 'CHAdeMO', 62.50, TRUE, TRUE),
    ('b0000004-0000-0000-0000-000000000001', 'a0000003-0000-0000-0000-000000000001', 'Type2_Tethered', 7.40, TRUE, TRUE),
    ('b0000005-0000-0000-0000-000000000001', 'a0000003-0000-0000-0000-000000000001', 'CCS', 50.00, FALSE, TRUE),
    ('b0000006-0000-0000-0000-000000000001', 'a0000004-0000-0000-0000-000000000001', 'Type2', 22.00, TRUE, TRUE),
    ('b0000007-0000-0000-0000-000000000001', 'a0000005-0000-0000-0000-000000000001', 'CCS', 150.00, TRUE, TRUE),
    ('b0000008-0000-0000-0000-000000000001', 'a0000005-0000-0000-0000-000000000001', 'CHAdeMO', 62.50, TRUE, TRUE),
    ('b0000009-0000-0000-0000-000000000001', 'a0000005-0000-0000-0000-000000000001', 'Type2', 22.00, TRUE, TRUE),
    ('b0000010-0000-0000-0000-000000000001', 'a0000005-0000-0000-0000-000000000001', 'Type2_Tethered', 7.40, FALSE, TRUE)
ON CONFLICT (id) DO NOTHING;
