[package]
name = "station-service"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "bornemap-backend"
path = "src/main.rs"

[lib]
name = "station_service"
path = "src/lib.rs"

[dependencies]
common-utils = { path = "../../libs/common-utils" }
actix-web.workspace = true
sqlx.workspace = true
utoipa.workspace = true
utoipa-swagger-ui.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
prometheus.workspace = true
jsonwebtoken.workspace = true
uuid.workspace = true
chrono.workspace = true
tokio.workspace = true
opening-hours.workspace = true
tracing-actix-web.workspace = true
dotenvy.workspace = true

[dev-dependencies]
testcontainers = "0.15"
testcontainers-modules = { version = "0.3", features = ["postgres"] }
reqwest.workspace = true
